Repository ThePay/api-client, pull requests merged in 2025-03, with the labels that each got.

#78 5909 nullable param fix
  src/Filter/PaymentsFilter.php
  src/Model/CreatePaymentCustomer.php
  src/Model/CreatePaymentParams.php
  src/Service/ApiService.php
  src/Service/ApiServiceInterface.php
  src/Service/GateService.php
  src/Service/GateServiceInterface.php
  src/TheClient.php
Labels: bug

#80 5909 sync 3.x with 2.x
  src/Filter/PaymentsFilter.php
  src/Model/CreatePaymentCustomer.php
  src/Model/CreatePaymentParams.php
  src/Service/ApiService.php
  src/Service/ApiServiceInterface.php
  src/Service/GateService.php
  src/Service/GateServiceInterface.php
  src/TheClient.php
Labels: bug, enhancement, PHP SDK

#83 V3.x merge from v2.x
  .github/workflows/ci.yml
Labels: PHP SDK
