Repository ThePay/api-client, pull requests merged in 2025-08, with the labels that each got.

#87 6286 is_customer_notification_enabled create payment parametr added
  src/Model/CreatePaymentParams.php
Labels: feature

#89 Merge v2 to v3
  src/Model/CreatePaymentParams.php
Labels: PHP SDK

#88 6179 remove payment creation using redirect
  .github/README.md
  doc/create-payment.md
  doc/index.md
  src/Model/SignedData.php
  src/Service/GateService.php
  src/Service/GateServiceInterface.php
  src/Service/SignatureService.php
  src/TheClient.php
  tests/CreatePaymentTest.php
Labels: enhancement
